version: '3'

services:
    postgres:
        image: postgres
        container_name: concurso-gastronomico-postgres
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: concurso-gastronomico
        ports:
            - 5432:5432
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
